### ISSUE TITLE
Support single-line comments

### ISSUE THREAD

**Issue by mrmurphy** [chenglou/language-reason#4]
Apparently, single line comments are supported now. VSCode's Reason plugin defaults to using `//` when doing both block comments and single-line comments now, and the compiler doesn't complain.

But when I open up the same file in Atom:

<img width="321" alt="image" src="https://user-images.githubusercontent.com/1227109/52802616-8ab88e80-303d-11e9-97ac-af8769dcee18.png">

The language doesn't appear to recognize `//` as a valid comment marker.

language-reason 0.0.4
ide-reason 1.1.7

**Comment by chenglou** [comment]
Sorry for the late update. Published as 0.0.5
