### ISSUE TITLE
Syntax highting over-highlights comment

### ISSUE THREAD

**Issue by Risto-Stevcev** [chenglou/language-reason#7]
Here on these lines it looks like the reasonml syntax highlighting fails to close the comments and continues highlighting the rest of the doc as a comment:

https://github.com/reasonml-community/bs-webapi-incubator/blob/bc0badfc40420e271f4b1703dd9c43bed7d68b13/src/Webapi/Webapi__Dom/Webapi__Dom__Node.re#L32-L55

**Comment by anmonteiro** [comment]
fixed in #6
